name: nta2
channels:
  - conda-forge

dependencies:
  - python=3.12
  - r-base=4.3
  - dask # Big data computing
  - distributed # Big data computing
  - matplotlib # Visualisation
  - mpltern # Visualisation (ternary plots)
  - numpy # In-memory arrays
  - pandas # In-memory dataframes
  - psutil # .virtual_memory() to get machine RAM
  - pyarrow # Streaming .feather -> .parquet
  - scipy # 3D ConvexHull to help render 3D neuropil outlines
  - tqdm # Progress bars (.feather -> .parquet)
  - pip
  
  # Install 3D visualisation/pyvista stack via pip
  # - Trame packages don't have fully supported conda forge builds
  # - conda's VTK is uncooperative on Windows so using pip's VTK instead
  # - The install order is crucial - pyvista checks if trame packages are available
  - pip: # order must be preserved here
      - trame # JS-Python framework for browser-rendering
      - trame-vuetify # UI components (including checkboxes)
      - trame-vtk # Browser-VTK interface
      - "pyvista[trame]" # Wraps VTK and Trame
      - vtk # The core GPU-accelerated visualisation engine