name: nta3
channels:
  - conda-forge

dependencies:
  - python=3.12
  - r-base=4.4
  - dask # Big data computing
  - distributed # Big data computing
  - ipykernel # Register conda environment with Jupyter
  - ipywidgets # Pyvista UI controls
  - matplotlib # Visualisation
  - mpltern # Visualisation (ternary plots)
  - notebook # Jupyter Notebook
  - numpy # In-memory arrays
  - pandas # In-memory dataframes
  - psutil # .virtual_memory() to get machine RAM
  - pyarrow # Streaming .feather -> .parquet
  - pyvista # 3D plotting
  - scipy # 3D ConvexHull to help render 3D neuropil outlines
  - tqdm # Progress bars (.feather -> .parquet)
  - pip
